baseURL = 'https://myblog-gilt-three.vercel.app/'
languageCode = 'en-us'
title = 'My Dev Blog'
theme = 'PaperMod'

[params]
  homeInfoParams = { Title = "Building 12 Tools in 12 Months", Content = "Documenting the journey from C programmer to indie hacker." }
  socialIcons = []
